### ISSUE TITLE
License and forking

### ISSUE THREAD

**Issue by samusgray** [AbleHealth/team#11]
Hi there,

This is an outstanding document! It resonates with me and reflects many unwritten principles that guide us at Healthify.us. We document similar things, but not quite what you've outlined here. For example, many of our engineering best practices are published in [our guides](https://github.com/healthify/guides).

We forked and heavily modified the above guides from Thoughtbot, who we've historically worked closely with, per the license agreement on that repo. I'm wondering if you'd like to add a creative commons license, or something to that effect, so we can fork, discuss, and modify this repo for Healthify's engineering teams.

We're working on the social determinants angle of health and hope y'all are crushing the value-based programs work! 

Cheers,
Aaron

**Comment by steveddaniels** [comment]
Hi @aaronagray great to hear you are interested in forking our culture guide! We have seen (and been impressed by) the Thoughtbot guides as well. Cool to see your team adapting them and making them your own. We are discussing licensing internally now.

**Comment by samusgray** [comment]
Thanks! I'll share with our team and see what come of it. Closing the issue now. 

Cheers,
Aaron

**Comment by steveddaniels** [comment]
@aaronagray all set! If you make use of it, we'd love to see the result :)

https://github.com/AbleHealth/team/blob/master/LICENSE.md

**Comment by samusgray** [comment]
Woohoo! 

We're currently working on revamped company values, which are more globally applicable to the organization. Once those are solidified next week we'll start talking about department values like these. Planning to use this as a demonstration of that and (if people agree it's a reasonable shortcut, given enough shared values between us) then we'll likely fork in then.

Thanks again!
